CREATE SCHEMA IF NOT EXISTS account;
CREATE SCHEMA IF NOT EXISTS article;

CREATE TABLE account.accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_non_locked BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    email VARCHAR(255) NOT NULL,
    email_verified BOOLEAN NOT NULL,
    failed_login_attempts INTEGER NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_login_at TIMESTAMP,
    last_name VARCHAR(255),
    locked_at TIMESTAMP,
    password VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP,
    username VARCHAR(255) NOT NULL,
    CONSTRAINT uk_accounts_email UNIQUE (email),
    CONSTRAINT uk_accounts_username UNIQUE (username)
);

CREATE INDEX idx_accounts_email ON account.accounts (email);
CREATE INDEX idx_accounts_username ON account.accounts (username);

CREATE TABLE account.account_roles (
    account_id BIGINT NOT NULL,
    role VARCHAR(255) NOT NULL,
    CONSTRAINT fk_account_roles_account
        FOREIGN KEY (account_id)
        REFERENCES account.accounts (id)
);

CREATE TABLE account.verification_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expire_at TIMESTAMP NOT NULL,
    purpose VARCHAR(255) NOT NULL,
    revoked_at TIMESTAMP,
    token VARCHAR(255) NOT NULL,
    used_at TIMESTAMP,
    CONSTRAINT uk_verification_token_token UNIQUE (token),
    CONSTRAINT fk_verification_token_account
        FOREIGN KEY (account_id)
        REFERENCES account.accounts (id)
);

CREATE INDEX idx_verification_token_account_purpose ON account.verification_token (account_id, purpose);
CREATE INDEX idx_verification_token_expire_at ON account.verification_token (expire_at);
CREATE INDEX idx_verification_token_lifecycle ON account.verification_token (used_at, revoked_at);

CREATE TABLE account.invite_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_created BOOLEAN NOT NULL,
    account_role VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    invited_by_account_id BIGINT NOT NULL,
    verification_token_id BIGINT NOT NULL,
    CONSTRAINT uk_invite_details_verification_token UNIQUE (verification_token_id),
    CONSTRAINT fk_invite_details_inviter
        FOREIGN KEY (invited_by_account_id)
        REFERENCES account.accounts (id),
    CONSTRAINT fk_invite_details_verification_token
        FOREIGN KEY (verification_token_id)
        REFERENCES account.verification_token (id)
);

CREATE INDEX idx_invite_details_email ON account.invite_details (email);
CREATE INDEX idx_invite_details_token ON account.invite_details (verification_token_id);
CREATE INDEX idx_invite_details_inviter ON account.invite_details (invited_by_account_id);
CREATE INDEX idx_invite_details_state ON account.invite_details (active, account_created);

CREATE TABLE account.reset_pass_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    account_id BIGINT NOT NULL,
    verification_token_id BIGINT NOT NULL,
    CONSTRAINT uk_reset_pass_details_verification_token UNIQUE (verification_token_id),
    CONSTRAINT fk_reset_pass_details_account
        FOREIGN KEY (account_id)
        REFERENCES account.accounts (id),
    CONSTRAINT fk_reset_pass_details_verification_token
        FOREIGN KEY (verification_token_id)
        REFERENCES account.verification_token (id)
);

CREATE INDEX idx_reset_pass_account_active ON account.reset_pass_details (account_id, active);
CREATE INDEX idx_reset_pass_token ON account.reset_pass_details (verification_token_id);

CREATE TABLE article.article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_status VARCHAR(255) NOT NULL,
    author_name VARCHAR(100) NOT NULL,
    author_account_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    published_at TIMESTAMP,
    slug VARCHAR(255) NOT NULL,
    title VARCHAR(150) NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT uk_article_slug UNIQUE (slug),
    CONSTRAINT fk_article_author
        FOREIGN KEY (author_account_id)
        REFERENCES account.accounts (id),
    CONSTRAINT ck_article_status
        CHECK (article_status IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT ck_article_publication_state
        CHECK (
            (article_status = 'DRAFT' AND published_at IS NULL)
            OR
            (article_status = 'PUBLISHED' AND published_at IS NOT NULL)
        )
);

CREATE INDEX idx_article_status_published_created
    ON article.article (article_status, published_at, created_at);

CREATE INDEX idx_article_author_status_created
    ON article.article (author_account_id, article_status, created_at);
